DELIMITER //
CREATE PROCEDURE delete_Shipments(
 IN _code varchar(10))
 
BEGIN
	DECLARE sID INT;
	SELECT SHIPMENT.ID INTO sID FROM SHIPMENT INNER JOIN ITEM ON SHIPMENT.ItemID = ITEM.ID AND ITEM.ItemCode = _code ORDER BY ShipmentDate DESC LIMIT 1;
    DELETE FROM SHIPMENT WHERE ID = sID;
END //
DELIMITER ;