DELIMITER //
CREATE PROCEDURE delete_Purchases(
 IN _code varchar(10))
 
BEGIN
	DECLARE pID INT;
	SELECT PURCHASE.ID INTO pID FROM PURCHASE INNER JOIN ITEM ON PURCHASE.ItemID = ITEM.ID AND ITEM.ItemCode = _code ORDER BY PurchaseDate DESC LIMIT 1;
    DELETE FROM PURCHASE WHERE ID = pID;
END //
DELIMITER ;