DELIMITER //
CREATE PROCEDURE get_All_Available()
 
BEGIN
	SELECT ITEM.ItemCode, ITEM.ItemDescription, SUM(IFNULL(SHIPMENT.Quantity,0))-SUM(IFNULL(PURCHASE.Quantity,0)) Available
	FROM ITEM 
	LEFT OUTER JOIN SHIPMENT ON ITEM.ID = SHIPMENT.ItemID 
	LEFT OUTER JOIN PURCHASE ON ITEM.ID = PURCHASE.ItemID
    GROUP BY ITEM.ItemCode ORDER BY ITEM.ID;
END //
DELIMITER ;