DELIMITER //
CREATE PROCEDURE get_Available(
 IN _code varchar(10))
 
BEGIN
	SELECT ITEM.ItemCode, ITEM.ItemDescription, SUM(IFNULL(SHIPMENT.Quantity,0))-SUM(IFNULL(PURCHASE.Quantity,0)) Available
	FROM ITEM 
	LEFT OUTER JOIN SHIPMENT ON ITEM.ID = SHIPMENT.ItemID 
	LEFT OUTER JOIN PURCHASE ON ITEM.ID = PURCHASE.ItemID 
	WHERE ITEM.ItemCode = _code;
END //
DELIMITER ;